name: Build and Publish bahmni-metabase Image
on:
  push:
    branches:
      - MOBN-2469

jobs:
  build-publish-docker:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Pull Github code
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t bahmni-metabase:latest -f package/docker/Dockerfile .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'bahmni-metabase:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          trivyignores: ./.trivyignore
          vuln-type: 'os,library'
          severity: 'CRITICAL'